version: '3.8'
services:
  captain_api:
    restart: always
    image: node:14.16.0-alpine
    command: >
      sh -c "
            NODE_ENV=${NODE_ENV} npm install && 
            NODE_ENV=${NODE_ENV} npm run db:createTable && 
            NODE_ENV=${NODE_ENV} npm run db:migrate && 
            NODE_ENV=${NODE_ENV} npm run db:seed && 
            NODE_ENV=${NODE_ENV} npm start"

    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - 'captain_db'

  captain_db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./config/mariadb:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: alfatih1453
