version: '3.8'
services:
  captain_api:
    restart: always
    image: node:14.16.0-alpine
    command: sh -c "NODE_ENV=production npm install --production && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - 'captain_db'
  captain_db:
    restart: always
    image: mysql:5.7
    volumes:
      - $HOME/db/captain-adventure/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: alfatih1453
