version: '3.8'
services:
  captain_api:
    image: node:14.16.0
    command:
      sh -c "NODE_ENV=production npm install --production && npm run db-reset &&
      npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - 'captain_db'
  captain_db:
    image: mysql:5.7
    volumes:
      - /home/db/captain-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: alfatih1453
